#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Remap keys.
xmodmap ~/.Xmodmap

# Disable that blasted speaker beeping.
xset -b

# If we're running in VirtualBox...
#VBoxClient-all &

# Fire off the window manager.
exec awesome
