#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Remap keys.
xmodmap ~/.Xmodmap

# Configure the cursor.
xrdb ~/.Xresources &

# Disable that blasted speaker beeping.
xset -b

# Go easy on the mouse acceleration.
xset m 4/3 10

# Remap caps lock to control, and use xcape to map control to escape if pressed
# and released on its own.
setxkbmap -option ctrl:nocaps
xcape -e "Control_L=Escape"

# If we're running in VirtualBox...
#VBoxClient-all &

# If we're running wireless...
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#nm-applet --sm-disable &

# Set the background.
sh ~/.fehbg &

# Start the notification daemon.
twmnd &

# Run Dropbox.
dropboxd &

# Fire off the window manager.
exec i3
